### ISSUE TITLE
[BUG] Flattened dependencies reported as children of the root/top node

### ISSUE THREAD

**Issue by dominykas** [npm/arborist#60] opened 2020-04-13 09:04 UTC
# What / Why

When the tree is flattened, deep dependencies are reported as direct dependencies, i.e. the `node.parent` will be the `node.root` rather than the dependent.

This may, of course, be as designed, in which case the documentation needs clarification. In that case, I can raise a separate feature request for detecting `node.direct` dependencies (i.e. ones in `package.json`, rather than just the top level of the `node_modules`) - or rename this issue.

## When

* n/a

## Where

* n/a

### Current Behavior

* `node.parent === node.root` when `node` is an indirect dependency.

### Steps to Reproduce

* `npm install debug`
* `arborist.buildIdealTree()`
* the `Node` for `ms` will have `node.parent.isTop === true`, even though its parent is `debug`.

### Expected Behavior

* The `Node` for `ms` should have `node.parent` be the `Node` for `debug`.

## Who

* n/a

## References

* n/a

**Comment by isaacs** [comment] 2020-04-28 00:31
You're confusing "tree on disk" with "dependency graph".  (It's a completely understandable confusion, since the docs are nowhere near where they ought to be, but we're moving fast and that hasn't been a top priority.)  This is actually working as designed, though.

When dealing with the tree of files and folders, you want to look at `parent`/`children` and `fsParent`/`fsChildren`.  This tells you what package is (or will be) unpacked in which node_modules folder.

When dealing with the graph of dependencies and dependents, you want to look at the `edgesOut` map and the `edgesIn` set.  An "Edge" represents a dependency relationship.

If you want to look at the _dependencies_ at the top level (or on any Node object), then you'd want `node.edgesOut`.  Each entry is a name mapped to an `Edge` object, which tells you the type of dep, and which node it'll resolve to.  If you want to know all the nodes resolving _to_ a given node, then you'd look at the `node.edgesIn` set.  This is a set, because obviously it can have more than one, and they're not keyed by name.  (The `name` on the edge is the name of the node you're looking at, since edges in a dep graph are directed.)

So, if a node is deduped up to the top level, then it ought to have the top node as its `parent`, and be listed in the top node's `children` map.  That's what that means.

Say it as a daily mantra:

* folder _tree_
* dependency _graph_

:)

**Closed by isaacs** 2020-04-28 00:31 UTC

**Comment by dominykas** [comment] 2020-06-06 15:08
Thanks! This makes it a lot more sense now!

At the risk of suggesting bloat, for my purposes, it would be handy to have a flat list of all the dependencies in the tree or at least some sort of a built-in `walk` function, even if it is easy enough to implement. The flat list is probably handier, as a [dumb walk](https://github.com/pkgjs/detect-node-support/blob/554ebf39500c8844e81f1c8a4508d211c36912b5/lib/deps.js#L18-L36) over `edgesOut`, starting at the `idealTree` means visiting some nodes multiple times.

My use case is to provide some analytics on each dependency, optionally including deep dependencies, optionally excluding dev dependencies.

**Comment by isaacs** [comment] 2020-06-06 22:31
Check out `tree.inventory`, probably has what you need.

All nodes in the tree:

```js
for (const node of tree.inventory.values()) {
  ...
}
```

All nodes matching a given name:

```js
for (const node of tree.inventory.query('name', someName)) {
  ...
}
```

All nodes matching some arbitrary filter function:

```
for (const node of tree.inventory.filter(node => { ... return true/false })) {
 ...
}
```

**Comment by isaacs** [comment] 2020-06-06 22:32
Also, we use the `treeverse` module quite a bit, which has built-in logic to avoid visiting the same node twice when a graph has cycles.  http://npm.im/treeverse

**Comment by dominykas** [comment] 2020-06-07 20:40
Thanks! `inventory` is exactly what I was looking for. And then checking whether a node is a direct dependency is a matter of checking whether the root node is inside the `edgesIn`.

**Comment by isaacs** [comment] 2020-06-14 18:11
Yep, that'd work!
